# bundle exec jekyll serve --host=0.0.0.0

title: MycilaRelay
description: Arduino / ESP32 library to control Electromagnetic and Solid State Relays
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
